# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: microsoft/dotnet:2.1-sdk-alpine

variables:
  project_name: XmlRPC
  configuration: Release

build:
  stage: build
  before_script:
    - apk add --no-cache git xmlstarlet
  script:
    - cd "${project_name}"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        MSG=$(git tag -l --format='%(contents)' $CI_COMMIT_TAG | xmlstarlet esc)
        xmlstarlet ed --inplace -u '/Project/PropertyGroup/Version' -v "$CI_COMMIT_TAG" "${project_name}.csproj"
        xmlstarlet ed --inplace -u '/Project/PropertyGroup/PackageReleaseNotes' -v "$MSG" "${project_name}.csproj"
      fi
    - dotnet restore "${project_name}.csproj"
    - dotnet build -c "${configuration}" "${project_name}.csproj"
    - dotnet pack -c "${configuration}" --include-symbols "${project_name}.csproj"
  artifacts:
    paths:
      - $PWD/${project_name}/bin/${configuration}/*.nupkg
  only:
    - master
    - tags

test:
  stage: test
  dependencies:
    - build
  script:
    - cd "${project_name}.Tests"
    - dotnet test "${project_name}.Tests.csproj"
  
publish-nuget:
  stage: deploy
  dependencies:
    - build
  script:
    - cd "${project_name}"
    - dotnet nuget push bin/"${configuration}"/${project_name}.$CI_COMMIT_TAG.nupkg -k $nuget_key -s nuget.org
    - dotnet nuget push bin/"${configuration}"/${project_name}.$CI_COMMIT_TAG.symbols.nupkg -k $nuget_key -s https://nuget.smbsrc.net/
  only:
    - tags

sast:
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
        --env SAST_ANALYZER_IMAGES=security-code-scan
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]
